# Generated by Django 5.2 on 2025-04-28 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_imagenservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenproducto',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='imagenservicio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='DetallePedido',
        ),
        migrations.DeleteModel(
            name='ImagenProducto',
        ),
        migrations.DeleteModel(
            name='ImagenServicio',
        ),
        migrations.DeleteModel(
            name='Pedido',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
