# Generated by Django 5.2 on 2025-05-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_perfilusuario_is_admin_perfilusuario_permisos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='tipo_cuenta',
            field=models.CharField(choices=[('empresa', 'Empresa'), ('usuario', 'Usuario')], default='usuario', help_text='¿Te registras como empresa o como consumidor?', max_length=10),
        ),
    ]
