# Generated by Django 5.2 on 2025-05-06 00:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_perfilusuario_tipo_cuenta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título principal de la página', max_length=200)),
                ('hero_image', models.URLField(blank=True, help_text='URL de la imagen de cabecera (hero)', null=True)),
                ('contenido', models.TextField(blank=True, help_text='Contenido HTML o texto enriquecido para la sección principal')),
                ('color_scheme', models.CharField(default='default', help_text='Esquema de color o tema para la página', max_length=50)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing_pages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
