# Generated by Django 5.2 on 2025-05-06 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_landingpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='descripcion',
            field=models.TextField(blank=True, help_text='Breve descripción o slogan de la empresa'),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='plantilla',
            field=models.CharField(choices=[('plantilla1', 'Plantilla Clásica'), ('plantilla2', 'Plantilla Moderna')], default='plantilla1', help_text='Selecciona el diseño de tu landing page', max_length=50),
        ),
    ]
