"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# Define la ruta base del proyecto para referencias relativas
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Clave secreta para la seguridad de la aplicación - ¡IMPORTANTE! Cambiar en producción
SECRET_KEY = 'django-insecure-@0gnsofvzar8!3#ecs+-_1h9=_4a#c5w297&k%bbh(45)o&wpk'

# SECURITY WARNING: don't run with debug turned on in production!
# Modo debug activado - Desactivar en producción
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

# Lista de aplicaciones instaladas en el proyecto
INSTALLED_APPS = [
    'django.contrib.admin',  # Panel de administración
    'django.contrib.auth',   # Sistema de autenticación
    'django.contrib.contenttypes',  # Framework de tipos de contenido
    'django.contrib.sessions',  # Framework de sesiones
    'django.contrib.messages',  # Framework de mensajes
    'django.contrib.staticfiles',  # Manejo de archivos estáticos
    'apps.accounts',  # Aplicación de cuentas de usuario
    'apps.productservice',  # Aplicación de productos y servicios
]

# Middleware - Componentes que procesan las peticiones/respuestas
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Seguridad
    'django.contrib.sessions.middleware.SessionMiddleware',  # Manejo de sesiones
    'django.middleware.common.CommonMiddleware',  # Funcionalidades comunes
    'django.middleware.csrf.CsrfViewMiddleware',  # Protección CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware',  # Autenticación
    'django.contrib.messages.middleware.MessageMiddleware',  # Mensajes
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  # Protección clickjacking
]

# Configuración de URLs principal
ROOT_URLCONF = 'core.urls'

# Configuración de templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Directorio de templates globales
        'APP_DIRS': True,  # Buscar templates en apps
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.accounts.views.user_profile_context',  # Contexto personalizado para perfil de usuario
            ],
        },
    },
]

# Configuración de WSGI
WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de la base de datos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # Motor de base de datos
        'NAME': BASE_DIR / 'db.sqlite3',  # Ubicación de la base de datos
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

# Validadores de contraseñas
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# Configuración de internacionalización
LANGUAGE_CODE = 'en-us'  # Idioma por defecto
TIME_ZONE = 'UTC'  # Zona horaria
USE_I18N = True  # Internacionalización
USE_TZ = True  # Soporte para zonas horarias


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Configuración de archivos estáticos
STATIC_URL = 'static/'  # URL base para archivos estáticos
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Directorio de archivos estáticos
]
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Directorio para archivos estáticos recolectados

# Configuración de archivos media (subidos por usuarios)
MEDIA_URL = '/media/'  # URL base para archivos media
MEDIA_ROOT = BASE_DIR / 'media'  # Directorio de archivos media

# Asegurarse que el directorio media existe
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT)

# Configuración del campo primario por defecto
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# URLs de redirección después de login/logout
LOGIN_REDIRECT_URL = 'home'  # Redirección después del login
LOGOUT_REDIRECT_URL = 'login'  # Redirección después del logout

# Configuración de correo electrónico
# EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Solo para desarrollo
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  # Backend SMTP para producción
EMAIL_HOST = 'smtp.gmail.com'  # Servidor SMTP
EMAIL_PORT = 587  # Puerto SMTP
EMAIL_USE_TLS = True  # Usar TLS para seguridad
EMAIL_HOST_USER = 'vctechmx@gmail.com'  # Usuario SMTP
EMAIL_HOST_PASSWORD = 'vycyysxlyrildgot'  # Contraseña SMTP
DEFAULT_FROM_EMAIL = 'Admin Panel <vctechmx@gmail.com>'  # Remitente por defecto
